// Lista dei comandi forniti dall'utente
const userCommands = [
  'DELAY', 'GO', 'SUB_SCRIPT', 'EXIT_MENU', 'SAY', 'CHANGECHAR', 'SET', 'ASK',
  'HIDECHAR', 'SHOWCHAR', 'RESET', 'LABEL', 'HIDEDLGSCENE', 'ADDOPPONENT',
  'SHOWPATH', 'SHOWDLGSCENE', 'RETURN', 'ANNOUNCE', 'SAYCHAR', 'SHOWNODE',
  'SETDECKPREPARATIONSCRIPT', 'SETSHIPTYPE', 'ADDPARTTOSHIP', 'FINISH_MISSION',
  'SET_TO', 'SHOWBUTTON', 'SETFOCUS', 'ADDPARTTOASIDESLOT', 'ADD', 'HIDEPATH',
  'ADDINFOWINDOW', 'ADDMISSIONCREDITS', 'HIDEBUTTON', 'SETSECRETADVPILE',
  'ACT_MISSION', 'SETADVPILE', 'CENTERMAPBYNODE', 'RESETFOCUS', 'SETSPECCONDITION',
  'ADDCREDITS', 'SHOWINFOWINDOW', 'MOVEPLAYERTONODE', 'SETACHIEVEMENTPROGRESS',
  'MODIFYOPPONENTSBUILDSPEED', 'SETACHIEVEMENTATTEMPT', 'ADDMISSIONCREDITSBYRESULT',
  'SUBOPPONENTCREDITSBYRESULT', 'SETFLIGHTDECKPREPARATIONSCRIPT', 'SETNODEKNOWN',
  'BUILDINGHELPSCRIPT', 'UNLOCKACHIEVEMENT', 'UNLOCKSHIPPLAN', 'ASKCHAR',
  'CENTERMAPBYPATH', 'SETTURNBASED', 'ADDSHIPPARTS', 'UNLOCKSHUTTLES',
  'SETMISSIONASFAILED', 'ALLSHIPSGIVEUP', 'HIDEALLPATHS', 'SETFOCUSIFCREDITS',
  'FLIGHTHELPSCRIPT', 'ADDOPPONENTSCREDITS', 'SETCREDITS', 'SETFLIGHTSTATUSBAR',
  'HIDENODE', 'ALIENHELPSCRIPT', 'GIVEUPFLIGHT', 'SETMISSIONASCOMPLETED',
  'SHOWHELPIMAGE', 'SAVESTATE', 'LOADSTATE', 'ADDNODE', 'FOCUSCHAR',
  'QUITCAMPAIGN', 'IF', 'MENU', 'OPT', 'BUILD', 'FLIGHT'
];

// Comandi nella categorizzazione
const categorizedCommands = [
  'SAY', 'DELAY', 'SET', 'RESET', 'GO', 'LABEL', 'SUB_SCRIPT', 'RETURN',
  'ASK', 'SAYCHAR', 'ASKCHAR', 'ANNOUNCE', 'SETFLIGHTSTATUSBAR',
  'SHOWCHAR', 'HIDECHAR', 'CHANGECHAR', 'FOCUSCHAR', 'SHOWDLGSCENE', 'HIDEDLGSCENE',
  'SET_TO', 'ADD',
  'SHOWPATH', 'HIDEPATH', 'HIDEALLPATHS', 'SHOWNODE', 'HIDENODE', 'SHOWBUTTON',
  'HIDEBUTTON', 'CENTERMAPBYNODE', 'CENTERMAPBYPATH', 'MOVEPLAYERTONODE',
  'SETFOCUS', 'RESETFOCUS', 'SETFOCUSIFCREDITS', 'SETNODEKNOWN', 'ADDNODE',
  'ADDOPPONENT', 'ADDOPPONENTSCREDITS', 'MODIFYOPPONENTSBUILDSPEED', 'SETSHIPTYPE',
  'SETDECKPREPARATIONSCRIPT', 'SETFLIGHTDECKPREPARATIONSCRIPT', 'SETADVPILE',
  'SETSECRETADVPILE', 'ADDPARTTOSHIP', 'ADDPARTTOASIDESLOT', 'SETSPECCONDITION',
  'ADDSHIPPARTS', 'ACT_MISSION', 'SETTURNBASED', 'SETMISSIONASFAILED',
  'SETMISSIONASCOMPLETED', 'ALLSHIPSGIVEUP', 'GIVEUPFLIGHT',
  'ADDCREDITS', 'SETCREDITS', 'ADDMISSIONCREDITS', 'ADDMISSIONCREDITSBYRESULT',
  'SUBOPPONENTCREDITSBYRESULT',
  'SETACHIEVEMENTPROGRESS', 'SETACHIEVEMENTATTEMPT', 'UNLOCKACHIEVEMENT',
  'UNLOCKSHIPPLAN', 'UNLOCKSHUTTLES',
  'ADDINFOWINDOW', 'SHOWINFOWINDOW', 'BUILDINGHELPSCRIPT', 'FLIGHTHELPSCRIPT',
  'ALIENHELPSCRIPT', 'SHOWHELPIMAGE',
  'SAVESTATE', 'LOADSTATE', 'QUITCAMPAIGN', 'EXIT_MENU',
  'IF', 'MENU', 'OPT', 'SCRIPT', 'MISSION', 'BUILD', 'FLIGHT'
];

// Trova comandi mancanti
const missing = userCommands.filter(cmd => !categorizedCommands.includes(cmd));

console.log('Comandi mancanti nella categorizzazione:');
console.log(missing);
console.log('\nTotale comandi utente:', userCommands.length);
console.log('Totale comandi categorizzati:', categorizedCommands.length);
console.log('Comandi mancanti:', missing.length);