@echo off
echo Stopping existing Node.js processes...
taskkill /F /IM node.exe >nul 2>&1
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting Galaxy Trucker Editor Server...
cd server
node server.js