- set__allParts_lots_of_3_and_4_connectors.yaml: 93  

#- set__alien_cyan.yaml: 3                        
#- set__alien_combined_cyan_brown.yaml: 1         
#- set__alien_combined_cyan_purple.yaml: 1


- set__cannon_bidirect.yaml: 3

- set__catapult.yaml: 5

- set_cargo.yaml: 1
- set__combined_cargo2_with_cargoSpec1.yaml: 2
- set__combined_cargo2_with_battery2.yaml: 2
- set__combined_cargoSpec1_with_battery2.yaml: 2

- set__plating.yaml: 4