- allParts-update8_lots_of_3_and_4_connectors.yaml: 89
- set__alien_cyan.yaml: 3
- set__alien_combined_cyan_brown.yaml: 1
- set__alien_combined_cyan_purple.yaml: 1

- set__cannon_bidirect.yaml: 3

- set__catapult.yaml: 5

- set_cargo.yaml: 3
- set__combined_cargo2_with_cargoSpec1.yaml: 2
- set__combined_cargo2_with_battery2.yaml: 2
- set__combined_cargoSpec1_with_battery2.yaml: 2

- set__plating.yaml: 4








#- set_alien_brown.yaml: 3
#- set_alien_purple.yaml: 3
#- set__alien_cyan.yaml: 3
#- set__alien_combined_cyan_brown.yaml: 1
#- set__alien_combined_cyan_purple.yaml: 1
#- set_cabin.yaml: 15
#- set_cannons.yaml: 26
#- set_engines.yaml: 18
#- set_shield.yaml: 5      
#- set_structural.yaml: 5
#- set_battery2.yaml: 5
#- set_battery3.yaml: 3
#- set_cargo.yaml: 6
#- set__combined_cargo2_with_cargoSpec1.yaml: 2
#- set__combined_cargo2_with_battery2.yaml: 2
#- set__combined_cargoSpec1_with_battery2.yaml: 2
#- set__plating.yaml: 3