- set_alien_brown.yaml: 3
- set_alien_purple.yaml: 3
- set__alien_cyan.yaml: 3
- set__alien_combined_cyan_brown.yaml: 1
- set__alien_combined_cyan_purple.yaml: 1
- set_cabin.yaml: 13       #15
- set__cabinVIP.yaml: 3

- set_cannons.yaml: 5             #17, 26, 23, 20
- set__cannon_bidirect.yaml: 1     #3, 18
- set__cannon_engine.yaml: 1       #3

- set__catapult.yaml: 8   #25,5,7
- set_engines.yaml: 20    #18

- set_shield.yaml: 5
- set_structural.yaml: 4

- set_battery2.yaml: 6  #5
- set_battery3.yaml: 4  #3
- set_cargo.yaml: 6        #7,6
- set__combined_cargo2_with_cargoSpec1.yaml: 2
- set__combined_cargo2_with_battery2.yaml: 2
- set__combined_cargoSpec1_with_battery2.yaml: 2
- set__plating.yaml: 4  #4


- set_ingot_value1.yaml: 13
- set_ingot_value2.yaml: 9
- set_ingot_value3.yaml: 3

#
#
#
#- set_alien_brown.yaml: 4
#- set_alien_purple.yaml: 4
#- set_battery2.yaml: 8
#- set_battery3.yaml: 4
#- set_cabin.yaml: 14
#- set_cannons.yaml: 26
#- set_cargo.yaml: 16
#- set_engines.yaml: 18
#- set_shield.yaml: 5
#- set_structural.yaml: 5
#  total: 104
#
#- set_alien_brown.yaml: 6
#- set_alien_purple.yaml: 6
#- set_battery2.yaml: 11
#- set_battery3.yaml: 7
#- set_cabin.yaml: 20
#- set_cannons.yaml: 40
#- set_cargo.yaml: 25
#- set_engines.yaml: 27
#- set_shield.yaml: 8
#- set_structural.yaml: 8
#  total: 158