- set_alien_brown.yaml: 4
- set_alien_purple.yaml: 4
- set_cabin.yaml: 14
- set_engines.yaml: 18
- set_shield.yaml: 5
- set_structural.yaml: 5
#
- set_battery2.yaml: 8
- set_battery3.yaml: 5
- set_cargo.yaml: 5
- set__combined_cargo2_with_cargoSpec1.yaml: 2
- set__combined_cargo2_with_battery2.yaml: 2
- set__combined_cargoSpec1_with_battery2.yaml: 2
#
- set_cannons.yaml: 15
- set__cannon_bidirect.yaml: 16
#
#- set__cannon_engine.yaml: 5
#
#
#- set_alien_brown.yaml: 4
#- set_alien_purple.yaml: 4
#- set_cabin.yaml: 14
#- set_cannons.yaml: 26
#- set_engines.yaml: 18
#- set_shield.yaml: 5
#- set_structural.yaml: 5
#- set_battery2.yaml: 3
#- set_battery3.yaml: 2
#- set_cargo2.yaml: 1
#- set_cargo3.yaml: 1
#- set_cargoSpec1.yaml: 1
#- set_cargoSpec2.yaml: 1
#- set__combined_cargo2_with_cargoSpec1.yaml: 3
#- set__combined_cargo2_with_battery2.yaml: 3
#- set__combined_cargoSpec1_with_battery2.yaml: 3
#  total: 94
#
#- set_alien_brown.yaml: 4
#- set_alien_purple.yaml: 4
#- set_battery2.yaml: 8
#- set_battery3.yaml: 4
#- set_cabin.yaml: 14
#- set_cannons.yaml: 26
#- set_cargo.yaml: 16
#- set_engines.yaml: 18
#- set_shield.yaml: 5
#- set_structural.yaml: 5
#  total: 104