name: "multiplayer_mission0"                    # id of mission name string - localized 
missionID: 0                                    # serial number of the mission


# Mission Config Example

# examples of rules
# no card changes
# no tile changes




        #gameType:                              # Values: realtime/turnbased; If mentioned this value can not be changed in a lobby by player.

fligthsAvailabelToChange: [STI, STII, STIII]    # Which flights can be turned on/off in a lobby by player. Other flights are locked.
                                                # For example we want STI to be optional, STII to by off and STIII to by always on. 
                                                # Setting will looks like this - (fligthsAvailabelToChange [STI], flightsPicked [STI, STIII])
flightsPicked: [STI]                            # Can be set instead off 'fligthsAvailabelToChange' and 'flightsPicked'. 
                                                # Can define some special order of flights. In lobby, flights are grayed and locked. Should be explained in mission rules.

playersCount: [2, 4]                            # [min, max]. Default is [2, 4]. Min can not be less then 2.


# ==== CARDS ====
universalDeckScript: mm_Default_Deck            # Used as digital and rough. (user can choose from 2 decks by default: digital and rough)
        #customDeckScript:                      # Special custom deck, that doesn't fit to any deck category. If custom, digital and rough are set, user can choose from 3 decks.

        #deckScript: MMAdvRadioactive           # Adventure cards deck building script
        #originalDeckScript:                    # Set if you want classic deck script
        #digitalDeckScript:                     # Use if you want set digital and rough separately
        #roughDeckScript:                       # Use if you want set digital and rough separately


# ==== TILES ====                               # Config file with list of all parts. Use 'pileConfig' or 'pileListConfig'.
pileConfigSTI:   default.yaml
pileConfigSTII:  default.yaml
pileConfigSTIII: default.yaml


# ==== SHIPS ====                               # Names of all available ship plans. If not mentioned default plans will be used. Should by only one ship plan for one flight.
shipPlans: [I, II, III]


# ==== RULES ====
        #evaluationConfig: radioactiveEvaluation-yaml # define evaluation in config file or here under 'evaluation' 
evaluation:                                     # You can mention only those values you want edit. But you have to repeat (copy&paste) the rules for each flight.
  STI:
    loctCrewMemeber: 0
    deliveredCrewMember: 0
    cargoValues: [1, 2, 3, 4] # [blue, green, yellow, red]
    bestLookingShipReward: 2
    finalPositionReward: [4, 3, 2, 1] # [first, second, third, fourth]
    finalPositionCoef: 1
    positionFocusCoes: 0 # ak si bol prvy n-krat za sebou, odmena sa ti nasobi n*_positionFocusCoef krat
    bestLookingFocusCoef: 0 # ak si ziskal najkrajsiu lod n-krat za sebou, odmena sa ti nasobi n*_beautyFocusCoef krat
    leastCannonsReward: 0
    mostCannonsReward: 0
    didNotLooseAnyPartReward: 0
    wholeShipPlanCoveredReward: 0 # All slots of ship plan were used.
    wholeShipPlanCoveredFinishBonus: 0 # All slots of ship plan were used and flight was finished successfully.
    
    ingotCargoValues: [[0,-2], [1, 2], [2,3], [4,5]] # [[count, credits_reward]] - if delivered ingots higher or equal to count, player gets credits_reward
    explosiveCargoValues: [[0, 0]]
    radioactiveCargoValues: [[0, 0]]
    fragileCargoValues: [[0, 0]]

    penaltyForLostIngot: 0
    penaltyForLostRadioactive: 0
    penaltyForLostFragile: 0
    penaltyForLostEplosive: 0

    giveupIfNoIngots: false
    giveupIfNoRadioactive: false
    giveupIfNoExplosives: false
    giveupIfNoFragile: false

    specialTilesTripletBonus: 0

    mostRadioactvieTilesBonus: 0
    mostFragileTilesBonus: 0
    mostExplosiveTilesBonus: 0
    highestWeightOfIngotsBonus: 0

    afterCardDistanceToZero: false
    afterOpenSpaceDistanceToZero: false


  STII:
    loctCrewMemeber: -2
    deliveredCrewMember: 2
  STIII:
    loctCrewMemeber: -4
    deliveredCrewMember: 4


# ==== Infoboards ====
InfoBoards:
  - default: [true, ship_plans_preview_double.png]
  - boardname: "tutorial/infoGameGoal.png"

