savePath: "saves/"
campaignSavePath: "campaignSaves/"
tmpPath: "tmp/"
CustomScriptsPath: "customScripts/"
CampaignScriptsPath: "campaign/campaignScripts/"
version: 900
client_api_version: 4002
GCGroupPrefix: "grp." # prefix of group grom Game Center
leaderboar: "grp.GTOnlineRank" #name of leaderboard
GooglePlayMapping: googleplay.yaml # to connect cge id's with google play id's (achievements, leaderboards)

# default server names are production, test, dev
servers:
  dev:
    IP: 151.236.219.214 
    port: [5000, 500, 50000]
  test:
    IP: 151.236.219.214
    port: [5001, 501, 50001]
  production:
    IP: 178.79.176.178
    port: [5000, 500, 50000] 
  local:
    IP: 127.0.0.1
    port: [50001]

languages: 
    EN: "English"
    CS: "Čeština"
    DE: "Deutsch"
    FR: "Français"
    RU: "Русский"
   # RO: "Român"
    ES: "Español"
    PL: "Polski"
   # IT: "Italiano"

# GooglePlay expansion. Used only for GooglePlay version. Do not use expansion setting if app do not use expansion.
expansion:
  name: "com.czechgames.galaxytrucker"
  version: 2007001

crashReport:
  url: "https://login.cge.as/bugreport.php"
  gameID: "GT"