# Syntaxe:
#
# ID_VE_HRE_NEMENIT: soubor.ogg
# ID1: cesta/soubor.ogg
# ID2: [soubor.ogg, 1.0]				                                hlasitost muze byt od 0.0 do 1.0, defaultne 1.0
# ID3: [[soubor1.ogg, 0.8], [soubor2.ogg, 0.9], [soubor3.ogg, 0.7]]     seznam zvuku, ze kterych bude nahodne vybran jeden
# ID4_TOHLE_NEJDE: [soubor1.ogg, soubor2.ogg, soubor3.ogg]              kdyz chces nahodny zvuk, musis dopsat i hlasitosti
#

# obecne zvuky
Button: [[button1.ogg, 1.0], [button1.ogg, 0.5]]
InfoWindow: button2.ogg
AchievementUnlocked: flight/power_up_engine.ogg
Star: star.ogg
Success: success.ogg
Failure: fail.ogg
Record: new_record.ogg

#main menu
knock: knock.ogg

#startgamemenu
StartSelectAI: button1.ogg

# building phase
PaPNextPlayerWindow: button1.ogg
PaPNextPlayerWindowClose: button1.ogg
BuildShowAdventureCards: build/peekadventurecards.ogg
BuildOpponentShowAdventureCards: [build/peekadventurecards.ogg, 0.5]
BuildHideAdventureCards: build/peekadventurecards.ogg
BuildOpponentHideAdventureCards: [build/peekadventurecards.ogg, 0.5]
BuildStartCountdown: build/startcountdown.ogg
BuildTickCountdown: build/countdown.ogg
BuildTakePart: build/takingpart.ogg
BuildOpponentTakePart: [build/takingpart.ogg, 0.5]
BuildDropPartOnShip: build/droppingpart1.ogg
BuildOpponentDropPartOnShip: [build/droppingpart1.ogg, 0.5]
BuildDropPartOnAsideSlot: build/droppingpart1.ogg
BuildOpponentDropPartOnAsideSlot: [build/droppingpart1.ogg, 0.5]
BuildTakeOrdinal: build/takingorder.ogg
BuildFlipPart: build/flippart.ogg
BuildOpponentFlipPart: [build/flippart.ogg, 0.5]
BuildWelding: build/welding1.ogg
BuildOpponentWelding: [build/welding1.ogg, 0.5]
BuildWrongPlace: build/wrongplace3.ogg
BuildEndTurn: button1.ogg
BuildTimeElapsed: build/wrongplace3.ogg

# flight phase
FlightStart: flight/start.ogg
FlightStardust: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightEpidemic: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightOpenspace: flight/open_space_move.ogg
FlightSabotage: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightSlavers: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightPirates: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightSmugglers: [[flight/negative1.ogg, 1.0], [flight/negative2.ogg, 1.0]]
FlightAbandonedShip: flight/abandonedship.ogg         
FlightAbandonedStation: flight/abandonedstation.ogg   
FlightMeteoric: flight/meteors.ogg
FlightPlanets: build/flippart.ogg                     # zatim chybi
FlightCombatZone: flight/combatzone.ogg 

FlightPickBattery: flight/pick_battery.ogg
FlightUnpowerPart: flight/pick_battery.ogg
FlightPowerUpEngine: flight/power_up_engine.ogg
FlightPowerUpGun: flight/power_up_gun.ogg
FlightPowerUpCatapultCargo: flight/armor_hit.ogg
FlightPowerUpCatapultCrew: [[flight/catapult_load_crew1.ogg, 1.0], [flight/catapult_load_crew2.ogg, 1.0], [flight/catapult_load_crew3.ogg, 1.0]]
FlightPowerUpShield: flight/power_up_shield.ogg
FlightOpenspaceMoveShips: flight/open_space_move.ogg
FlightMoveShipBackwards: flight/move_back.ogg
FlightPlunder: flight/plunder.ogg
FlightJetpack: flight/jetpack.ogg
FlightAbandonedShipCrewEnter: flight/abandoned_ship_crew_enter.ogg
FlightAbandonedShipIgnite: flight/abandoned_ship_ignite.ogg
FlightPiratesFire: flight/gunfire2.ogg
FlightPlayerFire: flight/gunfire1.ogg
FlightPlanetsIn: flight/planets_in.ogg
FlightPlanetsOut: flight/planets_out.ogg
FlightGiveUp: flight/planets_out.ogg
FlightSabotageBombTick: flight/sabotage_bomb_tick.ogg
FlightCatapultFire: flight/catapult_shot.ogg
FlightCatapultScream: [[flight/catapult_scream.ogg, 1.0], [flight/catapult_scream1.ogg, 1.0], [flight/catapult_scream2.ogg, 1.0], [flight/catapult_scream3.ogg, 1.0]]

FlightBlackhole: flight/blackhole_reveal.ogg
FlightBlackholeLoop: flight/blackhole_loop.ogg
FlightBlackholeSuck: flight/blackhole_vcuc.ogg
FlightJunkyard: flight/junkyard_reveal.ogg

FlightDiplomatParty: flight/diplomat_party.ogg

FlightPartDestroyed: flight/ship_explosion.ogg
#pouzije sa ak z lodi odpadne viac ako 5 dielikov
FlightMassiveShipBreak: flight/ship_explosion_massive.ogg

FlightSmallMeteorFlying: [flight/meteor_small.ogg, 0.1]
FlightLargeMeteorFlying: [flight/meteor_large.ogg, 0.2]
FlightBlastFlying: [flight/blast.ogg, 0.2]
FlightMeteorBounce: [flight/bounce.ogg, 0.25]
FlightMeteorDestroyed: flight/meteor_destroyed.ogg
FlightShieldRunning: [flight/shield_running.ogg, 0.5]
FlightPlatingBounce: flight/armor_hit.ogg

#faze ziskavani zkusenosti a zvysovani ranku po dokonceni online hry

#meni se cislo po jednotkach (postupne z 0 treba do 50 nebo tak neco)
RankScoreChange: score_change.ogg
#plni se progressbar
RankAdvanceProgressBar: rank/advance_progressbar.ogg
#progressbar dosahne 100% naplneni - mozna tam budem chtit dat nejaky ohnostroj nebo hvezdicky ktere vytrysknou z konce progressbaru
RankReachFullProgressBar: rank/reach_full_progressbar.ogg
#zvuk kdyz se ukazuje nove dosazeny rank
RankCelebrateNewRank: rank/celebrate_new_rank.ogg
#tohle je kdyz se objevi obrazke, ze jsem vydelal nejake kredity nebo ze jsem prodelal kalhoty
RankShowCriterionImage: rank/show_criterion_image.ogg

#lobby
#chatova zprava
msg: "lobby/msg.ogg"